# Generated by Django 2.2.4 on 2021-06-15 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_project_app', '0001_initial'),
        ('blog_app', '0002_auto_20210610_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='login_project_app.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='login_project_app.Usuario'),
            preserve_default=False,
        ),
    ]
