# Generated by Django 2.2.4 on 2021-06-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_project_app', '0001_initial'),
        ('blog_app', '0003_auto_20210615_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_who_liked',
            field=models.ManyToManyField(through='blog_app.Like', to='login_project_app.Usuario'),
        ),
    ]
